# ExioNAICS Emissions Estimation\n\nLoading and exploring the ExioNAICS dataset linking company NAICS codes to ExioML emissions data.

In [1]:
import os
from pathlib import Path
os.chdir(Path().absolute().parent)
print(os.getcwd())
print(os.listdir())

/Users/eunjaehong/Desktop
['..pdf', '.DS_Store', 'T mobile', 'Spring 2026.png', '~$Lab3.docx', '.localized', 'DS 201', 'uni stuff', 'Fox Lab', '~$3285 lab 7 report (final).docx', 'ClimateTurtles-ExioNaics-LLM-emissions-estimation', 'DS 205', '.git', '.vscode', '~$b 10 Report.docx', 'CAMS 508', '~$b report templete for eg.docx', 'CAMS 101']

In [2]:
import pandas as pd

df = pd.read_csv('ClimateTurtles-ExioNaics-LLM-emissions-estimation/ExioNAICS.csv')

print(f"Shape: {df.shape}")
print(f"\nColumns:\n{df.columns.tolist()}")
df.head()

Shape: (20535, 29)

Columns:
['Company Name', 'Company Description', 'NAICS Code', 'NAICS Title', '2022 NAICS Code', '2022 NAICS Title', '2017 NAICS Code', '2017 NAICS Title', 'Description', 'NAICS_5 Code', 'NAICS_5 Title', 'NAICS_5 Description', 'NAICS_4 Code', 'NAICS_4 Title', 'NAICS_4 Description', 'NAICS_3 Code', 'NAICS_3 Title', 'NAICS_3 Description', 'NAICS_2 Code', 'NAICS_2 Title', 'NAICS_2 Description', 'ExioML', 'region', 'Value Added [M.EUR]', 'Employment [1000 p.]', 'GHG emissions [kg CO2 eq.]', 'Energy Carrier Net Total [TJ]', 'Year', 'Carbon Intensity']

,Company Name,Company Description,NAICS Code,NAICS Title,2022 NAICS Code,2022 NAICS Title,2017 NAICS Code,2017 NAICS Title,Description,NAICS_5 Code,...,NAICS_2 Title,NAICS_2 Description,ExioML,region,Value Added [M.EUR],Employment [1000 p.],GHG emissions [kg CO2 eq.],Energy Carrier Net Total [TJ],Year,Carbon Intensity
0,Foot Locker Specialty Inc,Foot Locker Inc (Foot Locker) is a specialty r...,448150,Clothing Accessories Stores,458110,Clothing and Clothing Accessories Retailers,448150,Clothing Accessories Stores,This industry comprises establishments primari...,45811,...,Retail Trade,The Sector as a Whole\n\nThe Retail Trade sect...,"Retail trade services, except of motor vehicl...",US,155839.081079,26252.194517,1.974719e+08,3603.462783,2022,0.001267
1,Cengage Learning Inc,Cengage is the education and technology compan...,511130,Book Publishers,513130,Book Publishers,511130,Book Publishers,This industry comprises establishments known a...,51313,...,Information,The Sector as a Whole\n\nThe Information secto...,Printed matter and recorded media (22),US,101252.173354,359.127253,8.762522e+09,269198.419669,2022,0.086542
2,Cardinal Scale Mfg Co,Cardinal Scale Manufacturing Company manufactu...,333997,Scale and Balance Manufacturing,333998,All Other Miscellaneous General Purpose Machin...,333997,Scale and Balance Manufacturing,This U.S. industry comprises establishments pr...,33399,...,Manufacturing,The Sector as a Whole\n\nThe Manufacturing sec...,"Medical, precision and optical instruments, wa...",US,163416.090875,242.560449,6.744317e+09,172060.328352,2022,0.041271
3,Alticor Inc,Alticor Inc. owns and manages manufacturing an...,454390,Other Direct Selling Establishments,441330,Automotive Parts and Accessories Retailers,454390,Other Direct Selling Establishments,This industry comprises establishments primari...,44133,...,Retail Trade,The Sector as a Whole\n\nThe Retail Trade sect...,"Retail trade services, except of motor vehicl...",US,155839.081079,26252.194517,1.974719e+08,3603.462783,2022,0.001267
4,S Butler-Rosboro Corporation,Rosboro is North America's largest producer of...,335110,Electric Lamp Bulb and Part Manufacturing,335139,Electric Lamp Bulb and Other Lighting Equipmen...,335110,Electric Lamp Bulb and Part Manufacturing,This U.S. industry comprises establishments pr...,33513,...,Manufacturing,The Sector as a Whole\n\nThe Manufacturing sec...,Electrical machinery and apparatus n.e.c. (31),US,68675.538658,809.436143,3.051654e+09,101481.364669,2022,0.044436

In [4]:
df.dtypes

Company Name                         str
Company Description                  str
NAICS Code                         int64
NAICS Title                          str
2022 NAICS Code                    int64
2022 NAICS Title                     str
2017 NAICS Code                    int64
2017 NAICS Title                     str
Description                          str
NAICS_5 Code                       int64
NAICS_5 Title                        str
NAICS_5 Description                  str
NAICS_4 Code                       int64
NAICS_4 Title                        str
NAICS_4 Description                  str
NAICS_3 Code                       int64
NAICS_3 Title                        str
NAICS_3 Description                  str
NAICS_2 Code                       int64
NAICS_2 Title                        str
NAICS_2 Description                  str
ExioML                               str
region                               str
Value Added [M.EUR]              float64
Employment [1000 p.]             float64
GHG emissions [kg CO2 eq.]       float64
Energy Carrier Net Total [TJ]    float64
Year                               int64
Carbon Intensity                 float64
dtype: object

In [5]:
df[['GHG emissions [kg CO2 eq.]', 'Energy Carrier Net Total [TJ]', 'Value Added [M.EUR]', 'Carbon Intensity']].describe()

,GHG emissions [kg CO2 eq.],Energy Carrier Net Total [TJ],Value Added [M.EUR],Carbon Intensity
count,2.053500e+04,2.053500e+04,2.053500e+04,20535.000000
mean,2.015215e+10,5.940001e+05,5.072454e+05,1.045377
std,4.089554e+10,8.295536e+05,6.669893e+05,11.388547
min,4.000249e+07,3.993563e+02,1.159420e+01,0.000829
25%,4.692428e+09,1.132304e+05,8.957599e+04,0.011579
50%,8.762522e+09,2.559767e+05,1.742608e+05,0.040340
75%,2.289523e+10,7.982216e+05,8.103529e+05,0.220712
max,1.217165e+12,9.534165e+06,2.773712e+06,262.462607

In [6]:
#check class balance between NAICS2 codes --> If yes, need to do stratified train/val/test split 
naics2_counts=df['NAICS_2 Title'].value_counts()
naics2_counts

NAICS_2 Title
Manufacturing                                                               7419
Wholesale Trade                                                             1980
Retail Trade                                                                1678
Professional, Scientific, and Technical Services                            1060
Transportation and Warehousing                                               880
Finance and Insurance                                                        790
Other Services (except Public Administration)                                768
Construction                                                                 740
Health Care and Social Assistance                                            700
Information                                                                  696
Administrative and Support and Waste Management and Remediation Services     692
Agriculture, Forestry, Fishing and Hunting                                   645
Real Estate and Rental and Leasing                                           524
Mining, Quarrying, and Oil and Gas Extraction                                459
Public Administration                                                        402
Arts, Entertainment, and Recreation                                          357
Accommodation and Food Services                                              264
Educational Services                                                         259
Utilities                                                                    152
Management of Companies and Enterprises                                       70
Name: count, dtype: int64

In [6]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
print(df['Company Description'][0]) # as sbert preprocesses data internally # printed these descriptions to see if we need to clean up tokens like '\n'
print(df['Description'][0])
print(df['NAICS_2 Description'][0])
print(df['NAICS_3 Description'][0])
print(df['NAICS_4 Description'][0])
print(df['NAICS_5 Description'][0])

Foot Locker Inc (Foot Locker) is a specialty retailer of athletic footwear and apparel.
This industry comprises establishments primarily engaged in retailing general or specialized lines of new clothing and clothing accessories, such as hats and caps, costume jewelry, gloves, handbags, ties, wigs, toupees, and belts.  These establishments may provide basic alterations, such as hemming, taking in or letting out seams, or lengthening or shortening sleeves.

Cross-References. Establishments primarily engaged in--
The Sector as a Whole

The Retail Trade sector comprises establishments primarily engaged in retailing merchandise, generally without transformation, and rendering services incidental to the sale of merchandise.

The retailing process is the final step in the distribution of merchandise; retailers are, therefore, organized to sell merchandise in small quantities to the general public.  Retail stores are fixed point-of-sale locations, located and designed to attract a high volume of walk-in customers.  In general, retail stores have extensive displays of merchandise and use mass-media advertising to attract customers.  Retailers often reach customers and market merchandise with methods other than, or in addition to, physical stores, such as Internet websites, the broadcasting of "infomercials," the broadcasting and publishing of direct-response advertising, the publishing of paper and electronic catalogs, door-to-door solicitation, in-home demonstration, selling from portable stalls (street vendors, except food), and distribution through vending machines.  Establishments engaged in the direct sale and home delivery of products, such as home heating oil dealers and home delivery newspaper routes, are included here.

Retail establishments typically sell merchandise to the general public for personal or household consumption, but some also serve business and institutional clients.  These include office supply retailers, computer and software retailers, building materials dealers, plumbing supply retailers, and electrical supply retailers.

In addition to retailing merchandise, some retailers are also engaged in the provision of after-sales services, such as repair and installation.  For example, new automobile dealers, electronics and appliance retailers, and musical instrument and supplies retailers often provide repair services.  As a general rule, establishments engaged in retailing merchandise and providing after-sales services are classified in this sector.

Retail trade establishments are grouped into industries and industry groups typically based on one or more of the following criteria:

(a) The merchandise line or lines carried; for example, specialty retailers are distinguished from general-line retailers.

(b) The usual trade designation of the establishments.  This criterion applies in cases where a retailer is well recognized by the industry and the public, but difficult to define strictly in terms of merchandise lines carried; for example, pharmacies and department stores.

(c) Human resource requirements in terms of expertise; for example, the staff of an automobile dealer requires knowledge in financing, registering, and licensing issues that are not necessary in other retail industries.

The buying of goods for resale is a characteristic of retail trade establishments that particularly distinguishes them from establishments in the agriculture, manufacturing, and construction industries.  For example, farms that sell their products at or from the point of production are not classified in retail, but rather in agriculture.  Similarly, establishments that both manufacture and sell their products to the general public are not classified in retail, but rather in manufacturing.  However, establishments that engage in processing activities incidental to retailing are classified in retail.  This includes optical goods retailers that grind lenses, and meat and seafood retailers that process carcasses into cuts.

Wholesalers also engage in the buying of goods for resale, but they are not usually organized to serve the general public.  They typically operate from a warehouse or office, and neither the design nor the location of these premises is intended to solicit a high volume of walk-in traffic.  Wholesalers supply institutional, industrial, wholesale, and retail clients; their operations are, therefore, generally organized to purchase, sell, and deliver merchandise in larger quantities.  However, dealers of durable nonconsumer goods, such as farm machinery and heavy-duty trucks, are included in wholesale trade even if they often sell these products in single units.

Industries in the Clothing, Clothing Accessories, Shoe, and Jewelry Retailers subsector retail new clothing, clothing accessories, shoes, jewelry, luggage, and leather goods.

This industry group comprises establishments primarily engaged in operating coin- or card-operated or similar self-service laundries and drycleaners; providing drycleaning and laundry services (except coin- or card-operated); and supplying, on a rental or contract basis, laundered items (e.g., uniforms, gowns, shop towels, etc.).  Included in this industry group are establishments primarily engaged in supplying and servicing coin- or card-operated laundry and drycleaning equipment in places of business operated by others, such as apartments and dormitories.

This industry comprises establishments primarily engaged in retailing general or specialized lines of new clothing and clothing accessories, such as hats and caps, costume jewelry, gloves, handbags, ties, wigs, toupees, and belts.  These establishments may provide basic alterations, such as hemming, taking in or letting out seams, or lengthening or shortening sleeves.

Cross-References. Establishments primarily engaged in--

In [3]:
# drop NAICS2 column and set it as y --> then do a stratified train/val/test split as the 80/10/10 (same way from paper)
from sklearn.model_selection import train_test_split

train_andval, test=train_test_split(df,test_size=0.1,stratify=df['NAICS_2 Title'],random_state=192)
train, val=train_test_split(train_andval, test_size=0.125,stratify=train_andval['NAICS_2 Title'],random_state=192)

stratify_check1=train['NAICS_2 Title'].value_counts(normalize=True)
stratify_check2=val['NAICS_2 Title'].value_counts(normalize=True)
stratify_check3=test['NAICS_2 Title'].value_counts(normalize=True)

print(stratify_check1)

NAICS_2 Title
Manufacturing                                                               0.361286
Wholesale Trade                                                             0.096413
Retail Trade                                                                0.081694
Professional, Scientific, and Technical Services                            0.051639
Transportation and Warehousing                                              0.042857
Finance and Insurance                                                       0.038466
Other Services (except Public Administration)                               0.037415
Construction                                                                0.036054
Health Care and Social Assistance                                           0.034075
Information                                                                 0.033890
Administrative and Support and Waste Management and Remediation Services    0.033704
Agriculture, Forestry, Fishing and Hunting                                  0.031354
Real Estate and Rental and Leasing                                          0.025541
Mining, Quarrying, and Oil and Gas Extraction                               0.022325
Public Administration                                                       0.019604
Arts, Entertainment, and Recreation                                         0.017378
Accommodation and Food Services                                             0.012863
Educational Services                                                        0.012616
Utilities                                                                   0.007421
Management of Companies and Enterprises                                     0.003401
Name: proportion, dtype: float64

In [8]:
print(stratify_check2)

NAICS_2 Title
Manufacturing                                                               0.361315
Wholesale Trade                                                             0.096495
Retail Trade                                                                0.081783
Professional, Scientific, and Technical Services                            0.051493
Transportation and Warehousing                                              0.042839
Finance and Insurance                                                       0.038511
Other Services (except Public Administration)                               0.037213
Construction                                                                0.035915
Health Care and Social Assistance                                           0.034184
Administrative and Support and Waste Management and Remediation Services    0.033752
Information                                                                 0.033752
Agriculture, Forestry, Fishing and Hunting                                  0.031588
Real Estate and Rental and Leasing                                          0.025530
Mining, Quarrying, and Oil and Gas Extraction                               0.022501
Public Administration                                                       0.019472
Arts, Entertainment, and Recreation                                         0.017309
Accommodation and Food Services                                             0.012981
Educational Services                                                        0.012549
Utilities                                                                   0.007356
Management of Companies and Enterprises                                     0.003462
Name: proportion, dtype: float64

In [9]:
print(stratify_check3)

NAICS_2 Title
Manufacturing                                                               0.361246
Wholesale Trade                                                             0.096397
Retail Trade                                                                0.081792
Professional, Scientific, and Technical Services                            0.051607
Transportation and Warehousing                                              0.042843
Finance and Insurance                                                       0.038462
Other Services (except Public Administration)                               0.037488
Construction                                                                0.036027
Information                                                                 0.034080
Health Care and Social Assistance                                           0.034080
Administrative and Support and Waste Management and Remediation Services    0.033593
Agriculture, Forestry, Fishing and Hunting                                  0.031646
Real Estate and Rental and Leasing                                          0.025316
Mining, Quarrying, and Oil and Gas Extraction                               0.022395
Public Administration                                                       0.019474
Arts, Entertainment, and Recreation                                         0.017527
Accommodation and Food Services                                             0.012658
Educational Services                                                        0.012658
Utilities                                                                   0.007303
Management of Companies and Enterprises                                     0.003408
Name: proportion, dtype: float64

In [4]:
from sentence_transformers import SentenceTransformer 
import torch 
import torch.nn as nn

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
def loss_mnr (z1,z2,temperature=0.07):
    z1=F.normalize(z1,dim=1)
    z2=F.normalize(z2,dim=1)
    sim_matrix=(z1@z2.T)/temperature 
    diagonal_labels=torch.arange(z1.size(0),device=z1.device) 
    z1_loss=F.cross_entropy(sim_matrix,diagonal_labels)
    z2_loss=F.cross_entropy(sim_matrix.T,diagonal_labels)
    total_loss=(z1_loss+z2_loss)/2
    return total_loss

In [6]:
class SBERTClassifier(nn.Module):
    def __init__(self,model_sbert,num_classes):
        super().__init__()
        self.pretrained=model_sbert
        self.emb_dim=model_sbert.get_sentence_embedding_dimension()
        self.projector=nn.Linear(self.emb_dim,128)
        self.classifier=nn.Linear(self.emb_dim,num_classes)
    
    def forward(self,texts):
        embedding=self.pretrained.encode(texts,convert_to_tensor=True,device=device).clone()
        z1=self.projector(embedding)
        z2=self.projector(embedding)
        logit=self.classifier(embedding)
        return z1,z2,logit

In [ ]:
# no need to make into strings of "31,32,33" the same NAICS 2 codes like Manufacturing, Retail Trade (44,45), and Transportation and warehousing (48,49)
# since I did label encoding for the NAICS_2 Titles, not the NAICS2 codes.

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['NAICS_2 Label']=encoder.fit_transform(df['NAICS_2 Title'])
train['NAICS_2 Label']=encoder.transform(train['NAICS_2 Title'])
val['NAICS_2 Label']=encoder.transform(val['NAICS_2 Title'])
test['NAICS_2 Label']=encoder.transform(test['NAICS_2 Title'])

from torch.utils.data import DataLoader 
loader_train=DataLoader(list(zip(train['Company Description'].tolist(),train['NAICS_2 Description'].tolist(),
train['NAICS_2 Label'].tolist())),batch_size=32,shuffle=True,drop_last=True)
loader_val=DataLoader(list(zip(val['Company Description'].tolist(),val['NAICS_2 Description'].tolist(),
val['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)
loader_test=DataLoader(list(zip(test['Company Description'].tolist(),test['NAICS_2 Description'].tolist(),
test['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)

In [8]:
num_classes=df['NAICS_2 Title'].nunique()
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
device=torch.device('cpu')
model.to(device)
criterion=nn.CrossEntropyLoss() # classifying companies into NAICS2 code

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7635.17it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
import torch.nn.functional as F 

for epoch in range (5):
    model.train()
    loss_total=0

    for company_description,naics2_description, naics2_labels in loader_train: 
        naics2_labels=torch.tensor(naics2_labels).to(device)
        optimizer.zero_grad()
        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.1)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        loss_total+=combine_loss.item()

/var/folders/fk/7vtzncmx00v7h7vhq2nnqq5m0000gn/T/ipykernel_78645/3806442892.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  naics2_labels=torch.tensor(naics2_labels).to(device)

KeyboardInterrupt:

In [23]:
# torch.save(model.state_dict(),'sbert_5epochs_32batch.pt') 
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_hyperparameter_best.pt'))
model.to(device) # bring back saved model and do a warm-up 

model.train()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5473.51it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [35]:
from transformers import get_linear_schedule_with_warmup 
import torch.nn.functional as F 

epochs_num=5
steps_total=len(loader_train)*epochs_num
warmups_total=int(0.1*steps_total)

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=get_linear_schedule_with_warmup(optimizer,num_warmup_steps=warmups_total,num_training_steps=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.1)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Current epoch {one_epoch+1}, loss {current_loss}")

Current epoch 1, loss 5.750945469884589
Current epoch 2, loss 5.356878351457048
Current epoch 3, loss 5.171927853386001
Current epoch 4, loss 5.058343080954977
Current epoch 5, loss 5.002611024308913

In [43]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_10epochs.pt') # 10 total since original 5 + warm-up 5 epochs

In [45]:
print(os.getcwd())
print(os.path.exists('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_10epochs.pt'))

/Users/eunjaehong/Desktop
True

In [47]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_10epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=10
steps_total=len(loader_train)*epochs_num
warmups_total=int(0.1*steps_total)

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=get_linear_schedule_with_warmup(optimizer,num_warmup_steps=warmups_total,num_training_steps=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.1)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+11}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6198.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 11, loss 4.974306288804158
Total epoch 12, loss 4.83724990504803
Total epoch 13, loss 4.687264093078009
Total epoch 14, loss 4.550595251876529
Total epoch 15, loss 4.441975978341433
Total epoch 16, loss 4.357230880000804
Total epoch 17, loss 4.29036494906586
Total epoch 18, loss 4.253852171000868
Total epoch 19, loss 4.220766542453577
Total epoch 20, loss 4.203813241259886

In [48]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_20epochs.pt') # 20 total since original 5 + warm-up 15 epochs

In [75]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_20epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=5
steps_total=len(loader_train)*epochs_num

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=torch.optim.lr_scheduler.LinearLR(optimizer,start_factor=1.0,end_factor=0.1,total_iters=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.1)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+21}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7013.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 21, loss 4.179838388745147
Total epoch 22, loss 4.08854704989065
Total epoch 23, loss 4.014759528754961
Total epoch 24, loss 3.960961931530792
Total epoch 25, loss 3.9289642215955376

In [76]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_25epochs.pt') # 25 total since original 5 + warm-up 15 epochs + normal 5 epochs

In [80]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_25epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=10
steps_total=len(loader_train)*epochs_num

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=torch.optim.lr_scheduler.LinearLR(optimizer,start_factor=1.0,end_factor=0.1,total_iters=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+25}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7609.89it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 25, loss 3.7762070245081834
Total epoch 26, loss 3.695215595358669
Total epoch 27, loss 3.6203013826124737
Total epoch 28, loss 3.557584558147015
Total epoch 29, loss 3.5091514644056265
Total epoch 30, loss 3.4524542851023154
Total epoch 31, loss 3.4112053800337385
Total epoch 32, loss 3.376824875161199
Total epoch 33, loss 3.3571680352239324
Total epoch 34, loss 3.3429018879881

In [81]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_35epochs.pt') # 35 total since original 5 + warm-up 15 epochs  + normal 15 epochs(accidentally started epoch count at 25 above)

In [18]:
import torch.nn.functional as F 

pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_35epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=5
steps_total=len(loader_train)*epochs_num

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=torch.optim.lr_scheduler.LinearLR(optimizer,start_factor=1.0,end_factor=0.1,total_iters=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+36}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6532.59it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 36, loss 3.3318064585770713
Total epoch 37, loss 3.272946775549709
Total epoch 38, loss 3.240724740170016
Total epoch 39, loss 3.1996991143368256
Total epoch 40, loss 3.175036549804234

In [19]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_40epochs.pt') # 40 total since original 5 + warm-up 15 epochs  + normal 20 epochs

In [20]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_40epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=10
steps_total=len(loader_train)*epochs_num

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=torch.optim.lr_scheduler.LinearLR(optimizer,start_factor=1.0,end_factor=0.1,total_iters=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+41}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7011.95it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 41, loss 3.1586358481114454
Total epoch 42, loss 3.116829871187116
Total epoch 43, loss 3.0836955589823205
Total epoch 44, loss 3.0478890050755867
Total epoch 45, loss 3.0217041766289436
Total epoch 46, loss 2.994466216965477
Total epoch 47, loss 2.9775891436208592
Total epoch 48, loss 2.9575048423049473
Total epoch 49, loss 2.952209932025116
Total epoch 50, loss 2.932334302675606

In [21]:
torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_50epochs.pt') # 50 total since original 5 + warm-up 15 epochs  + normal 30 epochs

In [22]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_50epochs.pt'))
model.to(device) # bring back saved model 

model.train()

epochs_num=10
steps_total=len(loader_train)*epochs_num

optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)
schedule=torch.optim.lr_scheduler.LinearLR(optimizer,start_factor=1.0,end_factor=0.1,total_iters=steps_total)

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    print(f"Total epoch {one_epoch+51}, loss {current_loss}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6553.90it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Total epoch 51, loss 2.9378734838844527

KeyboardInterrupt:

In [29]:
# torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_60epochs.pt') # 60 total since original 5 + warm-up 15 epochs + normal 40 epochs
# due to loss increase this will not be saved. 
# current best model is the frozen backbone sbert at 35 epochs

In [25]:
# try an unfrozen backbone implementation 
from sentence_transformers import util 

def loss_mnr2 (z1,z2,temperature=0.1): # change temperature to be more balanced 
    z1=F.normalize(z1,dim=1)
    z2=F.normalize(z2,dim=1)
    sim_matrix=(z1@z2.T)/temperature 
    diagonal_labels=torch.arange(z1.size(0),device=z1.device) 
    z1_loss=F.cross_entropy(sim_matrix,diagonal_labels)
    z2_loss=F.cross_entropy(sim_matrix.T,diagonal_labels)
    total_loss=(z1_loss+z2_loss)/2
    return total_loss

class SBERTClassifier2(nn.Module):
    def __init__(self,model_sbert,num_classes):
        super().__init__()
        self.pretrained=model_sbert
        self.emb_dim=model_sbert.get_sentence_embedding_dimension()
        self.projector=nn.Linear(self.emb_dim,128)
        self.classifier=nn.Linear(self.emb_dim,num_classes)
    
    def forward(self,texts):
        encoded=self.pretrained.tokenize(texts)
        encoded=util.batch_to_device(encoded,device)
        output=self.pretrained(encoded)
        embedding=output.get('sentence_embedding')

        z1=self.projector(embedding)
        z2=self.projector(embedding)
        logit=self.classifier(embedding)
        return z1,z2,logit 

num_classes=df['NAICS_2 Title'].nunique()
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier2(pretrained,num_classes)
device=torch.device('cpu')
model.to(device)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6340.46it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier2(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [33]:
from transformers import get_linear_schedule_with_warmup 
epochs_num=20
steps_total=len(loader_train)*epochs_num
warmups_total=int(0.1*steps_total) # bring back the warm ups since we are doing the unfrozen backbone from scratch (+ will do early stopping this time)

optimizer=torch.optim.AdamW([{'params':model.pretrained.parameters(),'lr':2e-6},{'params':model.projector.parameters(),'lr':2e-5},
{'params':model.classifier.parameters(),'lr':2e-5},]) #smaller LR for backbone as it is unfrozen in this case 

schedule=get_linear_schedule_with_warmup(optimizer,num_warmup_steps=warmups_total,num_training_steps=steps_total)

acc1_best_val=0
zero_improvement=0

for one_epoch in range (epochs_num):
    model.train()
    loss_total=0
    for batch in loader_train:  
        company_description=batch[0]
        naics2_labels=batch[2].to(device)
        naics2_description=batch[1]

        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr2(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        schedule.step()

        loss_total+=combine_loss.item()
        current_loss=loss_total/len(loader_train)
    
    acc1_current_val=topk_accuracy(loader_val)[0]
    if acc1_current_val > acc1_best_val:
        acc1_best_val=acc1_current_val
        zero_improvement=0
        torch.save(model.state_dict(),'ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt')
        print(f"Total epoch {one_epoch+1}, loss {current_loss}, new best acc1 for val {acc1_best_val}")
    
    else: 
        zero_improvement+=1
        if zero_improvement>=3: # wait for 3 epochs when there are zero improvements
            print("Early Stopping for Best ACC1")
            break

ACC@1: 0.3146701388888889
ACC@3: 0.5160590277777778
ACC@5: 0.5928819444444444
ACC@10: 0.8038194444444444
Total epoch 1, loss 5.911051470690435, new best acc1 for val 0.3146701388888889
ACC@1: 0.4348958333333333
ACC@3: 0.6931423611111112
ACC@5: 0.8055555555555556
ACC@10: 0.9409722222222222
Total epoch 2, loss 5.3568713952999305, new best acc1 for val 0.4348958333333333
ACC@1: 0.5329861111111112
ACC@3: 0.8003472222222222
ACC@5: 0.8793402777777778
ACC@10: 0.9631076388888888
Total epoch 3, loss 4.970152973892665, new best acc1 for val 0.5329861111111112
ACC@1: 0.5737847222222222
ACC@3: 0.8172743055555556
ACC@5: 0.8927951388888888
ACC@10: 0.9600694444444444
Total epoch 4, loss 4.604883172252391, new best acc1 for val 0.5737847222222222
ACC@1: 0.6080729166666666
ACC@3: 0.83203125
ACC@5: 0.8958333333333334
ACC@10: 0.9535590277777778
Total epoch 5, loss 4.280936186384446, new best acc1 for val 0.6080729166666666
ACC@1: 0.59765625
ACC@3: 0.8302951388888888
ACC@5: 0.8962673611111112
ACC@10: 0.9535590277777778
ACC@1: 0.5920138888888888
ACC@3: 0.8159722222222222
ACC@5: 0.8815104166666666
ACC@10: 0.9375
ACC@1: 0.5920138888888888
ACC@3: 0.8190104166666666
ACC@5: 0.8858506944444444
ACC@10: 0.9479166666666666
Early Stopping for Best ACC1

In [9]:
def accuracy_topk (logit,labels,k):
    pred_classes_topk=logit.argsort(dim=1,descending=True)[:,:k]
    correct_bool=torch.eq(pred_classes_topk,labels.view(-1,1).expand(-1,k))
    return torch.any(correct_bool,dim=1).float().sum().item()

In [10]:
def topk_accuracy(loader):
    model.eval()
    acc1,acc3,acc5,acc10=0,0,0,0
    total=0

    with torch.no_grad():
        for company_description, naics2_description, label in loader: 
            label=torch.tensor(list(label)).to(device)
            logit=model(company_description)[2]
            acc1+=accuracy_topk(logit,label,k=1)
            acc3+=accuracy_topk(logit,label,k=3)
            acc5+=accuracy_topk(logit,label,k=5)
            acc10+=accuracy_topk(logit,label,k=10)
            total+=len(label)
    acc_1=acc1/total
    acc_3=acc3/total
    acc_5=acc5/total
    acc_10=acc10/total


    print("ACC@1:",acc_1)
    print("ACC@3:",acc_3)
    print("ACC@5:",acc_5)
    print("ACC@10:",acc_10)

    return acc_1,acc_3,acc_5,acc_10

In [34]:
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
topk_accuracy(loader_train)

ACC@1: 0.6607054455445545
ACC@3: 0.8758044554455445
ACC@5: 0.9284653465346535
ACC@10: 0.971039603960396

(0.6607054455445545, 0.8758044554455445, 0.9284653465346535, 0.971039603960396)

In [35]:
model.eval()
from sklearn.metrics import confusion_matrix
preds_all,labels_all=[],[]
with torch.no_grad():
        for company_description, naics2_description, label in loader_train: 
            label=torch.tensor(list(label)).to(device)
            logit=model(company_description)[2]
            predict=torch.argmax(logit,dim=1)
            labels_all.extend(label.cpu().numpy())
            preds_all.extend(predict.cpu().numpy())

resulting_matrix=pd.DataFrame(confusion_matrix(labels_all,preds_all),index=encoder.classes_,columns=encoder.classes_)
resulting_matrix.to_csv("confusion_matrix_best_unfrozen.csv")

In [67]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Downloading matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 10.0 MB/s eta 0:00:0000:010:01m
Downloading contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (270 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp311-cp311-macosx_10_9_universal2.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 10.3 MB/s eta 0:00:00 0:00:01
Downloading kiwisolver-1.5.0-cp311-cp311-macosx_11_0_arm64.whl (63 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pyparsing-3.3.2

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [36]:
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
topk_accuracy(loader_val)

ACC@1: 0.6080729166666666
ACC@3: 0.83203125
ACC@5: 0.8958333333333334
ACC@10: 0.9535590277777778

(0.6080729166666666, 0.83203125, 0.8958333333333334, 0.9535590277777778)

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
class_counts=train['NAICS_2 Label'].value_counts().sort_index()
normalized_weights=torch.tensor(1.0/class_counts.values,dtype=torch.float).to(device)
classifi_loss=F.cross_entropy(logit,naics2_labels,weight=normalized_weights,label_smoothing=0.1)

In [ ]:
#hyperparameter tuning (done and fixed above) --> cross validation --> then do test accuracy 
best_acc1=0
results_lst=[]
for learning_rates in [1e-5,3e-5,5e-5]:
    print(f"Current training in {learning_rates} lr")
    pretrained=SentenceTransformer("all-MiniLM-L6-v2")
    model=SBERTClassifier(pretrained,num_classes)
    model.to(device)
    optimizer=torch.optim.AdamW(model.parameters(),lr=learning_rates) #switched from sgd to adamW

    for epoch in range (5):
        model.train()
        loss_total=0

        for company_description,naics2_description, naics2_labels in loader_train: 
            naics2_labels=torch.tensor(list(naics2_labels)).to(device)
            optimizer.zero_grad()
            z1,_,_=model(company_description)
            z2,_,logit=model(naics2_description)
            contrast_loss=loss_mnr(z1,z2)
            classifi_loss=F.cross_entropy(logit,naics2_labels,weight=normalized_weights,label_smoothing=0.1)
            combine_loss=contrast_loss+classifi_loss
            combine_loss.backward()
            optimizer.step()
            loss_total+=combine_loss.item()
        print(f"current epoch{epoch+1},loss:{loss_total/len(loader_train)}") # fixed upon proofreading, but not run again to not interfere with the model with best hyperparameters

    accuracy_val1,accuracy_val3,accuracy_val5,accuracy_val10=topk_accuracy(loader_val)
    results_lst.append((learning_rates,accuracy_val1))
    print(f"When learning rate is {learning_rates}, ACC@1 for validation set is {accuracy_val1}")

    if accuracy_val1>best_acc1:
        best_acc1=accuracy_val1
        torch.save(model.state_dict(),'sbert_hyperparam_best.pt')
        print(f"current best sbert model saved")

print(max(results_lst,key=lambda x: x[1]),"is the best learning rate and best ACC@1 for Validation Set")

Current training in 1e-05 lr

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6084.61it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

current epoch1,loss:3381.619526386261
current epoch2,loss:3268.842127799988
current epoch3,loss:3208.1178073883057
current epoch4,loss:3164.1908497810364
current epoch5,loss:3127.3129653930664
ACC@1: 0.10243055555555555
ACC@3: 0.2348090277777778
ACC@5: 0.3337673611111111
ACC@10: 0.59375
When learning rate is 1e-05, ACC@1 for validation set is 0.10243055555555555
current best sbert model saved
Current training in 3e-05 lr

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6691.35it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

current epoch1,loss:3307.102838039398
current epoch2,loss:3143.7553191184998
current epoch3,loss:3054.4848284721375
current epoch4,loss:2984.6227917671204
current epoch5,loss:2919.7037773132324
ACC@1: 0.06336805555555555
ACC@3: 0.20616319444444445
ACC@5: 0.3025173611111111
ACC@10: 0.5160590277777778
When learning rate is 3e-05, ACC@1 for validation set is 0.06336805555555555
Current training in 5e-05 lr

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5980.09it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

current epoch1,loss:3233.332922935486
current epoch2,loss:3045.0468559265137
current epoch3,loss:2939.7794857025146
current epoch4,loss:2842.4662914276123
current epoch5,loss:2762.104836463928
ACC@1: 0.04861111111111111
ACC@3: 0.15104166666666666
ACC@5: 0.2686631944444444
ACC@10: 0.4973958333333333
When learning rate is 5e-05, ACC@1 for validation set is 0.04861111111111111
(1e-05, 0.10243055555555555) is the best learning rate and best ACC@1 for Validation Set

Note: The losses above are very large because they were previously not divided by len(loader_train), which account for the large numbers observed. When the losses for each epoch are divded by len(loader_train), then they are quite small.

In [ ]:
# as the models above with adamW optimizer were less effective than with SGD optimizer with lr=2e-05
# I will now do lr=1e-05 (best performing out of the 3 lrs) with SGD optimizer compare SGD optimizer lr=2e-05 (original)
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.to(device)
optimizer=torch.optim.SGD(model.parameters(),lr=1e-05,momentum=0.85) #switched back to SGD

for epoch in range (5):
    model.train()
    loss_total=0

    for company_description,naics2_description, naics2_labels in loader_train: 
        naics2_labels=torch.tensor(naics2_labels).to(device)
        optimizer.zero_grad()
        z1,_,_=model(company_description)
        z2,_,logit=model(naics2_description)
        contrast_loss=loss_mnr(z1,z2)
        classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.1) # no class weights (like original) to see if it improves 
        combine_loss=contrast_loss+classifi_loss
        combine_loss.backward()
        optimizer.step()
        loss_total+=combine_loss.item()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7253.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/var/folders/fk/7vtzncmx00v7h7vhq2nnqq5m0000gn/T/ipykernel_78645/4202064459.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  naics2_labels=torch.tensor(naics2_labels).to(device)

In [ ]:
torch.save(model.state_dict(),'sbert_5epochs_1e-05.pt') 
topk_accuracy(loader_val)

ACC@1: 0.09071180555555555
ACC@3: 0.2899305555555556
ACC@5: 0.4131944444444444
ACC@10: 0.6710069444444444

(0.09071180555555555,
 0.2899305555555556,
 0.4131944444444444,
 0.6710069444444444)

In [ ]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('sbert_5epochs_32batch.pt'))
model.to(device)
model.eval() 
topk_accuracy(loader_val)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5804.13it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ACC@1: 0.3289930555555556
ACC@3: 0.4587673611111111
ACC@5: 0.5347222222222222
ACC@10: 0.7048611111111112

(0.3289930555555556,
 0.4587673611111111,
 0.5347222222222222,
 0.7048611111111112)

In [ ]:
os.rename('sbert_5epochs_32batch.pt','sbert_hyperparameter_best.pt') #after comparing from all other combinations of hyperparameters above

In [57]:
# below are the results for sbert with frozen backbone and 5 epochs 

from sklearn.model_selection import StratifiedKFold
k_folds=StratifiedKFold(n_splits=5,shuffle=True,random_state=109)
cross_val_res=[]

train_andval['NAICS_2 Label']=encoder.transform(train_andval['NAICS_2 Title'])


for kth_fold,(idx_train,idx_val) in enumerate (k_folds.split(train_andval,train_andval['NAICS_2 Title'])):
    train_fold=train_andval.take(idx_train)
    val_fold=train_andval.take(idx_val)

    loader_train_fold=DataLoader(list(zip(train_fold['Company Description'].tolist(),train_fold['NAICS_2 Description'].tolist(),
    train_fold['NAICS_2 Label'].tolist())),batch_size=32,shuffle=True,drop_last=True)
    loader_val_fold=DataLoader(list(zip(val_fold['Company Description'].tolist(),val_fold['NAICS_2 Description'].tolist(),
    val_fold['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)

    pretrained=SentenceTransformer("all-MiniLM-L6-v2")
    model=SBERTClassifier2(pretrained,num_classes)
    model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_5epochs.pt'))
    model.to(device)
    model.eval() 

    for epoch in range (3):
        model.train()
        loss_total=0

        for company_description,naics2_description, naics2_labels in loader_train_fold: 
            naics2_labels=torch.tensor(naics2_labels).to(device)
            optimizer.zero_grad()
            z1,_,_=model(company_description)
            z2,_,logit=model(naics2_description)
            contrast_loss=loss_mnr2(z1,z2)
            classifi_loss=F.cross_entropy(logit,naics2_labels,label_smoothing=0.05)
            combine_loss=contrast_loss+classifi_loss
            combine_loss.backward()
            optimizer.step()
            schedule.step()
            loss_total+=combine_loss.item()
            current_loss=loss_total/len(loader_train)
        
    print(f"Current fold:{kth_fold+1}")
    acc1,acc3,acc5,acc10=topk_accuracy(loader_val_fold)
    cross_val_res.append((acc1,acc3,acc5,acc10))
        
for idx, kth in enumerate([1,3,5,10]):
    avg_accuracy=sum(r[idx]for r in cross_val_res)/len(cross_val_res)
    print(f"Average ACC@{kth} for validation set = {avg_accuracy}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7677.37it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/var/folders/fk/7vtzncmx00v7h7vhq2nnqq5m0000gn/T/ipykernel_78645/3495359177.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  naics2_labels=torch.tensor(naics2_labels).to(device)

Current fold:1
ACC@1: 0.07771739130434782
ACC@3: 0.21467391304347827
ACC@5: 0.38206521739130433
ACC@10: 0.6489130434782608

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7561.80it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:2
ACC@1: 0.05
ACC@3: 0.23206521739130434
ACC@5: 0.3535326086956522
ACC@10: 0.6144021739130435

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6076.05it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:3
ACC@1: 0.14184782608695654
ACC@3: 0.32255434782608694
ACC@5: 0.44483695652173916
ACC@10: 0.6614130434782609

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5755.42it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:4
ACC@1: 0.2361413043478261
ACC@3: 0.44483695652173916
ACC@5: 0.5652173913043478
ACC@10: 0.7032608695652174

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6354.91it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:5
ACC@1: 0.3184782608695652
ACC@3: 0.46141304347826084
ACC@5: 0.5429347826086957
ACC@10: 0.7168478260869565
Average ACC@1 for validation set = 0.16483695652173913
Average ACC@3 for validation set = 0.33510869565217394
Average ACC@5 for validation set = 0.45771739130434774
Average ACC@10 for validation set = 0.6689673913043479

In [38]:
# k-fold for unfrozen backbone sbert 

from sklearn.model_selection import StratifiedKFold
train_andval['NAICS_2 Label']=encoder.transform(train_andval['NAICS_2 Title'])
k_folds=StratifiedKFold(n_splits=5,shuffle=True,random_state=109)
cross_val_res=[]

for nth_fold,(idx_train,idx_val) in enumerate (k_folds.split(train_andval,train_andval['NAICS_2 Title'])):
    print(f"Fold {nth_fold+1}in progress")
    train_fold=train_andval.take(idx_train)
    val_fold=train_andval.take(idx_val)

    loader_train_fold=DataLoader(list(zip(train_fold['Company Description'].tolist(),train_fold['NAICS_2 Description'].tolist(),
    train_fold['NAICS_2 Label'].tolist())),batch_size=32,shuffle=True,drop_last=True)
    loader_val_fold=DataLoader(list(zip(val_fold['Company Description'].tolist(),val_fold['NAICS_2 Description'].tolist(),
    val_fold['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)

    pretrained=SentenceTransformer("all-MiniLM-L6-v2")
    model=SBERTClassifier2(pretrained,num_classes)
    model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
    model.to(device)
    model.eval()

    print(f"Current fold:{nth_fold+1}")
    acc1,acc3,acc5,acc10=topk_accuracy(loader_val_fold)
    cross_val_res.append((acc1,acc3,acc5,acc10))

for idx, kth in enumerate([1,3,5,10]):
    avg_accuracy=sum(r[idx]for r in cross_val_res)/len(cross_val_res)
    print(f"Average ACC@{kth} for validation set = {avg_accuracy}")

Fold 1in progress

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5730.15it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:1
ACC@1: 0.65625
ACC@3: 0.8690217391304348
ACC@5: 0.9233695652173913
ACC@10: 0.9682065217391305
Fold 2in progress

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8033.72it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:2
ACC@1: 0.6540760869565218
ACC@3: 0.8695652173913043
ACC@5: 0.9222826086956522
ACC@10: 0.9676630434782608
Fold 3in progress

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6006.53it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:3
ACC@1: 0.6432065217391304
ACC@3: 0.866304347826087
ACC@5: 0.9247282608695652
ACC@10: 0.9703804347826087
Fold 4in progress

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5386.77it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:4
ACC@1: 0.6614130434782609
ACC@3: 0.8801630434782609
ACC@5: 0.9304347826086956
ACC@10: 0.972554347826087
Fold 5in progress

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6040.03it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Current fold:5
ACC@1: 0.65625
ACC@3: 0.8671195652173913
ACC@5: 0.9220108695652174
ACC@10: 0.9657608695652173
Average ACC@1 for validation set = 0.6542391304347827
Average ACC@3 for validation set = 0.8704347826086958
Average ACC@5 for validation set = 0.9245652173913044
Average ACC@10 for validation set = 0.9689130434782609

In [21]:
# do test set evaluation on sbert best hyperparameter! 
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('sbert_hyperparameter_best.pt'))
model.to(device)
model.eval()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6280.82it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [25]:
# for frozen backbone sbert with 5 epochs 
loader_test=DataLoader(list(zip(test['Company Description'].tolist(),test['NAICS_2 Description'].tolist(),
test['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)
topk_accuracy(loader_test)

ACC@1: 0.3369140625
ACC@3: 0.43896484375
ACC@5: 0.50537109375
ACC@10: 0.6865234375

(0.3369140625, 0.43896484375, 0.50537109375, 0.6865234375)

In [11]:
import torch.nn.functional as F 

pretrained=SentenceTransformer("all-MiniLM-L6-v2") 
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_35epochs.pt'))
model.to(device) # bring back saved model of 35 epochs (frozen backbone)
model.eval() 

loader_test=DataLoader(list(zip(test['Company Description'].tolist(),test['NAICS_2 Description'].tolist(),
test['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)
topk_accuracy(loader_test)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6053.83it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ACC@1: 0.4052734375
ACC@3: 0.6845703125
ACC@5: 0.7900390625
ACC@10: 0.91259765625

(0.4052734375, 0.6845703125, 0.7900390625, 0.91259765625)

In [40]:
# do test set evaluation on sbert best hyperparameter for unfrozen backbone sbert
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier2(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
model.to(device)
model.eval() 

loader_test=DataLoader(list(zip(test['Company Description'].tolist(),test['NAICS_2 Description'].tolist(),
test['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)
topk_accuracy(loader_test)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7985.31it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ACC@1: 0.5986328125
ACC@3: 0.80615234375
ACC@5: 0.884765625
ACC@10: 0.94921875

(0.5986328125, 0.80615234375, 0.884765625, 0.94921875)

In [41]:
# predict ghg by multiplying carbon intensity of the naics 2 industry and actual company revenue (for all train, val, test sets)
# As topk accuracy for our project was for the NAICS2 Company classification, now we calculate the predicted ghg emssions for all companies in dataset 

loader_test_ghg=DataLoader(list(zip(test['Company Description'].tolist(),test['NAICS_2 Description'].tolist(),
test['NAICS_2 Label'].tolist(),test['Value Added [M.EUR]'].tolist(),test['GHG emissions [kg CO2 eq.]'].tolist())),batch_size=32,drop_last=True)

In [42]:
loader_train_ghg=DataLoader(list(zip(train['Company Description'].tolist(),train['NAICS_2 Description'].tolist(),
train['NAICS_2 Label'].tolist(),train['Value Added [M.EUR]'].tolist(),train['GHG emissions [kg CO2 eq.]'].tolist())),batch_size=32,shuffle=True,drop_last=True)

loader_val_ghg=DataLoader(list(zip(val['Company Description'].tolist(),val['NAICS_2 Description'].tolist(),
val['NAICS_2 Label'].tolist(),val['Value Added [M.EUR]'].tolist(),val['GHG emissions [kg CO2 eq.]'].tolist())),batch_size=32,drop_last=True)

In [61]:
from sklearn.metrics import mean_absolute_error
import numpy as np

def topk_accuracy_with_ghg(loader):

    model.eval()
    acc1,acc3,acc5,acc10=0,0,0,0
    total=0
    ghg_predict_acc1=np.array([])
    ghg_predict_acc3=np.array([])
    ghg_predict_acc5=np.array([])
    ghg_predict_acc10=np.array([])
    ghg_per_naics2=df.groupby('NAICS_2 Label')['Carbon Intensity'].mean().to_dict()

    carbon_predict=np.array([])
    truth_ghg_company=np.array([])

    with torch.no_grad():
        for company_description, naics2_description, label, company_revenue, co2 in loader: 
            label=torch.tensor(list(label)).to(device)
            company_revenue=torch.tensor(list(company_revenue),dtype=torch.float)
            co2=torch.tensor(list(co2),dtype=torch.float)
            logit=model(company_description)[2]

            pred_top10=logit.topk(10,dim=1).indices.cpu().numpy() 

            def pred_co2 (k): 
                return torch.tensor([np.mean([ghg_per_naics2[int(naics)]for naics in top10[:k]])for top10 in pred_top10]
                ,dtype=torch.float)*company_revenue*1000000

            ghg_predict_acc1=np.concatenate([ghg_predict_acc1,pred_co2(1).numpy()])
            ghg_predict_acc3=np.concatenate([ghg_predict_acc3,pred_co2(3).numpy()])
            ghg_predict_acc5=np.concatenate([ghg_predict_acc5,pred_co2(5).numpy()])
            ghg_predict_acc10=np.concatenate([ghg_predict_acc10,pred_co2(10).numpy()])

            truth_ghg_company=np.concatenate([truth_ghg_company,co2.numpy()])

            acc1+=accuracy_topk(logit,label,k=1)
            acc3+=accuracy_topk(logit,label,k=3)
            acc5+=accuracy_topk(logit,label,k=5)
            acc10+=accuracy_topk(logit,label,k=10)
            total+=len(label)
    acc_1=acc1/total
    acc_3=acc3/total
    acc_5=acc5/total
    acc_10=acc10/total
    def rmse_and_mae (company_ghg_pred):
        rmse=np.sqrt(np.mean((company_ghg_pred-truth_ghg_company)**2))
        mean_abs_error=mean_absolute_error(truth_ghg_company,company_ghg_pred)
        return rmse, mean_abs_error

    rmse_acc1,mae_acc1=rmse_and_mae(ghg_predict_acc1)
    rmse_acc3,mae_acc3=rmse_and_mae(ghg_predict_acc3)
    rmse_acc5,mae_acc5=rmse_and_mae(ghg_predict_acc5)
    rmse_acc10,mae_acc10=rmse_and_mae(ghg_predict_acc10)

    print("Mean ABS Error for GHG avg by top 1 NAICS2 predictions :",mae_acc1)
    print("RMSE for GHG by top 1 NAICS2 predictions:", rmse_acc1)

    print("Mean ABS Error for GHG avg by top 3 NAICS2 predictions :",mae_acc3)
    print("RMSE for GHG by top 3 NAICS2 predictions:", rmse_acc3)

    print("Mean ABS Error for GHG avg by top 5 NAICS2 predictions :",mae_acc5)
    print("RMSE for GHG by top 5 NAICS2 predictions:", rmse_acc5)

    print("Mean ABS Error for GHG avg by top 10 NAICS2 predictions :",mae_acc10)
    print("RMSE for GHG by top 10 NAICS2 predictions:", rmse_acc10)

    print("ACC@1 for NAICS2 Classification:",acc_1)
    print("ACC@3 for NAICS2 Classification:",acc_3)
    print("ACC@5 for NAICS2 Classification:",acc_5)
    print("ACC@10 for NAICS2 Classification:",acc_10)

    return acc_1,acc_3,acc_5,acc_10, rmse_acc1,mae_acc1, rmse_acc3,mae_acc3, rmse_acc5,mae_acc5, rmse_acc10,mae_acc10

In [62]:
topk_accuracy_with_ghg(loader_train_ghg)

Mean ABS Error for GHG avg by top 1 NAICS2 predictions : 320567515337.6708
RMSE for GHG by top 1 NAICS2 predictions: 3179554043884.314
Mean ABS Error for GHG avg by top 3 NAICS2 predictions : 234584945755.3211
RMSE for GHG by top 3 NAICS2 predictions: 1454130728915.1665
Mean ABS Error for GHG avg by top 5 NAICS2 predictions : 282104405183.60956
RMSE for GHG by top 5 NAICS2 predictions: 1180030371503.3193
Mean ABS Error for GHG avg by top 10 NAICS2 predictions : 398061336973.7548
RMSE for GHG by top 10 NAICS2 predictions: 979213725752.1849
ACC@1 for NAICS2 Classification: 0.6606435643564357
ACC@3 for NAICS2 Classification: 0.8758663366336633
ACC@5 for NAICS2 Classification: 0.9285272277227723
ACC@10 for NAICS2 Classification: 0.9709777227722772

(0.6606435643564357,
 0.8758663366336633,
 0.9285272277227723,
 0.9709777227722772,
 np.float64(3179554043884.314),
 320567515337.6708,
 np.float64(1454130728915.1665),
 234584945755.3211,
 np.float64(1180030371503.3193),
 282104405183.60956,
 np.float64(979213725752.1849),
 398061336973.7548)

In [63]:
topk_accuracy_with_ghg(loader_val_ghg)

Mean ABS Error for GHG avg by top 1 NAICS2 predictions : 324430205490.4582
RMSE for GHG by top 1 NAICS2 predictions: 3084791406594.098
Mean ABS Error for GHG avg by top 3 NAICS2 predictions : 242438940782.45953
RMSE for GHG by top 3 NAICS2 predictions: 1539881319574.2266
Mean ABS Error for GHG avg by top 5 NAICS2 predictions : 316021379028.755
RMSE for GHG by top 5 NAICS2 predictions: 1336635460700.0847
Mean ABS Error for GHG avg by top 10 NAICS2 predictions : 419451777282.24426
RMSE for GHG by top 10 NAICS2 predictions: 1070416747225.52
ACC@1 for NAICS2 Classification: 0.6080729166666666
ACC@3 for NAICS2 Classification: 0.83203125
ACC@5 for NAICS2 Classification: 0.8958333333333334
ACC@10 for NAICS2 Classification: 0.9535590277777778

(0.6080729166666666,
 0.83203125,
 0.8958333333333334,
 0.9535590277777778,
 np.float64(3084791406594.098),
 324430205490.4582,
 np.float64(1539881319574.2266),
 242438940782.45953,
 np.float64(1336635460700.0847),
 316021379028.755,
 np.float64(1070416747225.52),
 419451777282.24426)

In [64]:
topk_accuracy_with_ghg(loader_test_ghg)

Mean ABS Error for GHG avg by top 1 NAICS2 predictions : 311693298705.6907
RMSE for GHG by top 1 NAICS2 predictions: 3182393825667.936
Mean ABS Error for GHG avg by top 3 NAICS2 predictions : 219116471305.04663
RMSE for GHG by top 3 NAICS2 predictions: 1407189463082.11
Mean ABS Error for GHG avg by top 5 NAICS2 predictions : 268745694949.6775
RMSE for GHG by top 5 NAICS2 predictions: 1137626764288.5
Mean ABS Error for GHG avg by top 10 NAICS2 predictions : 408843780964.6577
RMSE for GHG by top 10 NAICS2 predictions: 1040687425415.3875
ACC@1 for NAICS2 Classification: 0.5986328125
ACC@3 for NAICS2 Classification: 0.80615234375
ACC@5 for NAICS2 Classification: 0.884765625
ACC@10 for NAICS2 Classification: 0.94921875

(0.5986328125,
 0.80615234375,
 0.884765625,
 0.94921875,
 np.float64(3182393825667.936),
 311693298705.6907,
 np.float64(1407189463082.11),
 219116471305.04663,
 np.float64(1137626764288.5),
 268745694949.6775,
 np.float64(1040687425415.3875),
 408843780964.6577)

In [22]:
# need to now test for out of distribution data for this sbert!! 

import re

In [23]:
# import ood dataset that combines the two ood datasets below that is finalized with NAICS2 code without embedding so it is consistent across different models 
ood_official=pd.read_csv('ClimateTurtles-ExioNaics-LLM-emissions-estimation/ood_dataset_official.csv')
print(ood_official.shape)
ood_official.head(2)

(36380, 5)

,company name,description,model_input,naics2_title,naics2_code
0,Hotel Sacher,"building in Innere Stadt, Vienna, Austria","Hotel Sacher. building in Innere Stadt, Vienna...",Accommodation and Food Services,72
1,Sberbank,Russian banking and financial services company,Sberbank. Russian banking and financial servic...,Finance and Insurance,52

In [26]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier2(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
model.to(device)
model.eval()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5888.39it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier2(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [27]:
ood_official['NAICS_2 Label']=encoder.transform(ood_official['naics2_title'])
num_classes=df['NAICS_2 Title'].nunique()
map_naics2_descriptions= dict(zip(df['NAICS_2 Label'],df['NAICS_2 Description']))

loader_official_ood=DataLoader(list(zip(ood_official['model_input'].tolist(), ood_official['NAICS_2 Label'].map(map_naics2_descriptions).tolist(),
ood_official['NAICS_2 Label'].tolist())),batch_size=32,drop_last=True)

In [28]:
topk_accuracy(loader_official_ood)

ACC@1: 0.6592484595070423
ACC@3: 0.8252640845070423
ACC@5: 0.8850132042253521
ACC@10: 0.9626705545774648

(0.6592484595070423,
 0.8252640845070423,
 0.8850132042253521,
 0.9626705545774648)

In [29]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_35epochs.pt')) #frozen backbone for reference
model.to(device)
model.eval() 

topk_accuracy(loader_official_ood)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5889.67it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ACC@1: 0.3517000440140845
ACC@3: 0.6039557658450704
ACC@5: 0.7268650968309859
ACC@10: 0.8759077904929577

(0.3517000440140845,
 0.6039557658450704,
 0.7268650968309859,
 0.8759077904929577)

In [18]:
clf = pd.read_csv('ClimateTurtles-ExioNaics-LLM-emissions-estimation/classification-dataset-v1.csv')
print(clf.shape)
clf.head(2)

(73974, 10)

,Category,website,company_name,homepage_text,h1,h2,h3,nav_link_text,meta_keywords,meta_description
0,Commercial Services & Supplies,bipelectric.com,bip dipietro electric inc,Electrici...,NaN,NaN,NaN,NaN,"electricians vero beach, vero beach electrical...","Providing quality, reliable full service resid..."
1,Healthcare,eliasmedical.com,elias medical,site map | en español Elias Medical h...,Offering Bakersfield family medical care from ...,Welcome to ELIAS MEDICAL#sep#Family Medical Pr...,Get To Know Elias Medical#sep#Family Medical P...,NaN,Elias Medical bakersfield ca family doctor med...,For the best value in Bakersfield skin care tr...

In [19]:
clf_ood = clf[['company_name', 'meta_description', 'Category']].copy()
clf_ood = clf_ood.rename(columns={'Category': 'label', 'meta_description': 'text'})
clf_ood = clf_ood.dropna(subset=['label', 'text']).reset_index(drop=True)

print(clf_ood.shape)
print(clf_ood['label'].value_counts())
clf_ood.head(3)

(66886, 3)
label
Professional Services             6655
Healthcare                        6534
Corporate Services                6442
Financials                        6278
Commercial Services & Supplies    5856
Media, Marketing & Sales          5798
Transportation & Logistics        5727
Information Technology            5426
Energy & Utilities                5162
Consumer Staples                  4906
Industrials                       3073
Consumer Discretionary            2611
Materials                         2418
Name: count, dtype: int64

,company_name,text,label
0,bip dipietro electric inc,"Providing quality, reliable full service resid...",Commercial Services & Supplies
1,elias medical,For the best value in Bakersfield skin care tr...,Healthcare
2,koops overhead doors,"Koops Overhead Doors specializes in the sales,...",Commercial Services & Supplies

In [20]:
clf_ood['text']

0        Providing quality, reliable full service resid...
1        For the best value in Bakersfield skin care tr...
2        Koops Overhead Doors specializes in the sales,...
3        We would like to welcome you to Midtown Eyecar...
4        Repro Security provide a range of tailor made ...
                               ...
66881    Nayyarsons Corporation offical website and por...
66882    Claddagh Coffee Cafe, located in Saint Paul, M...
66883    Advanced skin therapists with post grad qualif...
66884    Beauty Call can arrange a local, mobile, profe...
66885    Miracapo develops and manufactures high qualit...
Name: text, Length: 66886, dtype: str

In [30]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier(pretrained,num_classes)
model.load_state_dict(torch.load('sbert_hyperparameter_best.pt'))
model.to(device)
model.eval()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7772.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [21]:
pretrained=SentenceTransformer("all-MiniLM-L6-v2")
model=SBERTClassifier2(pretrained,num_classes)
model.load_state_dict(torch.load('ClimateTurtles-ExioNaics-LLM-emissions-estimation/sbert_best_unfrozen.pt'))
model.to(device)
model.eval()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6854.85it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SBERTClassifier2(
  (pretrained): SentenceTransformer(
    (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (projector): Linear(in_features=384, out_features=128, bias=True)
  (classifier): Linear(in_features=384, out_features=20, bias=True)
)

In [22]:
import torch.nn.functional as F 
# cosine similarity for closest NAICS2 label mapping 
naics2_embedding=model.pretrained.encode(list(encoder.classes_),convert_to_tensor=True,device='cpu')
clf_ood_embedding=model.pretrained.encode(clf_ood['label'].tolist(),convert_to_tensor=True,device='cpu')

similar_labels=F.cosine_similarity(clf_ood_embedding.unsqueeze(1),naics2_embedding.unsqueeze(0),dim=2)
_,idx_map=similar_labels.max(dim=1)
label_map=[encoder.classes_[ith.item()]for ith in idx_map]

In [23]:
clf_ood['label_naics2_mapped']=label_map
clf_ood_labels=encoder.transform(clf_ood['label_naics2_mapped'].tolist())
loader_clf_ood=DataLoader(list(zip(clf_ood['text'].tolist(),clf_ood['label_naics2_mapped'].tolist(),
clf_ood_labels.tolist())),batch_size=32,drop_last=True)

In [24]:
topk_accuracy(loader_clf_ood)

ACC@1: 0.421247009569378
ACC@3: 0.6110944976076556
ACC@5: 0.6999401913875598
ACC@10: 0.8276913875598086

(0.421247009569378, 0.6110944976076556, 0.6999401913875598, 0.8276913875598086)

In [26]:
# the second ood dataset (for testing)

wiki = pd.read_csv('ClimateTurtles-ExioNaics-LLM-emissions-estimation/wikidata_global_companies_info.csv', index_col=0)
print(wiki.shape)
wiki.head(2)

(3579, 9)

,wikidata_uri,company name,description,country,instance of,inception,official website,industry,founded by
0,http://www.wikidata.org/entity/Q279260,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",Austria,['hotel' 'Viennese coffee house'],1876-01-01,http://www.sacher.com/,['hotel'],Édouard Sacher
1,http://www.wikidata.org/entity/Q193326,Goldman Sachs,American investment bank,United States of America,['stock exchange' 'bank' 'multinational corpor...,1869-01-01,https://www.goldmansachs.com/,['financial services' 'financial sector'\n 'fi...,Samuel Sachs

In [27]:
def parse_industry(s):
    if pd.isna(s): return None
    s = re.sub(r"[\[\]']", '', str(s))
    return re.sub(r'\s+', ' ', s).strip() or None

wiki['industry_clean'] = wiki['industry'].apply(parse_industry)

wiki_ood = wiki[['company name', 'description', 'industry_clean']].copy()
wiki_ood = wiki_ood.rename(columns={'company name': 'company_name', 'description': 'text', 'industry_clean': 'label'})
wiki_ood = wiki_ood.dropna(subset=['label', 'text']).reset_index(drop=True)

print(wiki_ood.shape)
print(wiki_ood['label'].value_counts().head(10))
wiki_ood.head(3)

(3579, 3)
label
retail                 190
telecommunications     109
automotive industry    108
financial services      98
film industry           65
petroleum industry      63
filmmaking              54
video game industry     51
creative industries     49
software industry       47
Name: count, dtype: int64

,company_name,text,label
0,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",hotel
1,Goldman Sachs,American investment bank,financial services financial sector financial ...
2,Sberbank,Russian banking and financial services company,banking in Russia financial sector financial s...

In [28]:
# cosine similarity for closest NAICS2 label mapping for the second ood dataset 
wiki_ood_embedding=model.pretrained.encode(wiki_ood['label'].tolist(),convert_to_tensor=True,device='cpu')

wiki_similar_labels=F.cosine_similarity(wiki_ood_embedding.unsqueeze(1),naics2_embedding.unsqueeze(0),dim=2)
_,wiki_idx_map=wiki_similar_labels.max(dim=1)
wiki_label_map=[encoder.classes_[ith.item()]for ith in wiki_idx_map]

In [29]:
wiki_ood['label_naics2_mapped']=wiki_label_map
wiki_ood_labels=encoder.transform(wiki_ood['label_naics2_mapped'].tolist())
loader_wiki_ood=DataLoader(list(zip(wiki_ood['text'].tolist(),wiki_ood['label_naics2_mapped'].tolist(),
wiki_ood_labels.tolist())),batch_size=32,drop_last=True)

In [30]:
topk_accuracy(loader_wiki_ood)

ACC@1: 0.5149211711711712
ACC@3: 0.7612612612612613
ACC@5: 0.8440315315315315
ACC@10: 0.9414414414414415

(0.5149211711711712,
 0.7612612612612613,
 0.8440315315315315,
 0.9414414414414415)

In [30]:
# ood top k accuracies for the official_ood dataframe is above the previous attempts on the two separate ood datasets

# ACC@1 = 35, ACC@3 = 60, ACC@5 = 72, ACC@10=87 for the frozen backbone sbert 
# ACC@1 = 65, ACC@3 = 82, ACC@5 = 88, ACC@10=96 for the unfrozen backbone sbert (Improved significantly from its previous version!!)