In [1]:
import pandas as pd 

df = pd.read_csv('../wikidata_global_companies_info.csv') 
df.head()

,Unnamed: 0,wikidata_uri,company name,description,country,instance of,inception,official website,industry,founded by
0,0,http://www.wikidata.org/entity/Q279260,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",Austria,['hotel' 'Viennese coffee house'],1876-01-01,http://www.sacher.com/,['hotel'],Édouard Sacher
1,1,http://www.wikidata.org/entity/Q193326,Goldman Sachs,American investment bank,United States of America,['stock exchange' 'bank' 'multinational corpor...,1869-01-01,https://www.goldmansachs.com/,['financial services' 'financial sector'\n 'fi...,Samuel Sachs
2,2,http://www.wikidata.org/entity/Q205012,Sberbank,Russian banking and financial services company,Russia,['bank' 'public company' 'enterprise' 'busines...,1991-03-22,https://www.sberbank.com,['banking in Russia' 'financial sector'\n 'fin...,Central Bank of Russia
3,3,http://www.wikidata.org/entity/Q180855,Heineken,Dutch beer company,Netherlands,['brewery' 'public company' 'business' 'enterp...,1864-07-12,http://www.heinekeninternational.com/,['beverage industry'],Gerard Adriaan Heineken
4,4,http://www.wikidata.org/entity/Q66048,Deutsche Bank,German global banking and financial services c...,Germany,['bank' 'public company' 'universal bank'],1870-03-10,https://www.db.com,['financial services' 'Other monetary intermed...,Ludwig Bamberger

In [2]:
df2 = pd.read_csv('../wikidata_global_companies_info.csv') 
df2.head()

,Unnamed: 0,wikidata_uri,company name,description,country,instance of,inception,official website,industry,founded by
0,0,http://www.wikidata.org/entity/Q279260,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",Austria,['hotel' 'Viennese coffee house'],1876-01-01,http://www.sacher.com/,['hotel'],Édouard Sacher
1,1,http://www.wikidata.org/entity/Q193326,Goldman Sachs,American investment bank,United States of America,['stock exchange' 'bank' 'multinational corpor...,1869-01-01,https://www.goldmansachs.com/,['financial services' 'financial sector'\n 'fi...,Samuel Sachs
2,2,http://www.wikidata.org/entity/Q205012,Sberbank,Russian banking and financial services company,Russia,['bank' 'public company' 'enterprise' 'busines...,1991-03-22,https://www.sberbank.com,['banking in Russia' 'financial sector'\n 'fin...,Central Bank of Russia
3,3,http://www.wikidata.org/entity/Q180855,Heineken,Dutch beer company,Netherlands,['brewery' 'public company' 'business' 'enterp...,1864-07-12,http://www.heinekeninternational.com/,['beverage industry'],Gerard Adriaan Heineken
4,4,http://www.wikidata.org/entity/Q66048,Deutsche Bank,German global banking and financial services c...,Germany,['bank' 'public company' 'universal bank'],1870-03-10,https://www.db.com,['financial services' 'Other monetary intermed...,Ludwig Bamberger